spring.application.name=demo
server.port=8085

spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=kjk
spring.datasource.password=2006

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console